version: '3'

services:

  icat-db:
     build: ./postgres
#     restart: unless-stopped
     expose:
       - "5432"
     volumes:
       - pg_data:/var/lib/postgresql/data
     environment:
       POSTGRES_HOST_AUTH_METHOD: trust

  irods-icat:
    build: ./irods-icat
    hostname: irods-icat
     #restart: unless-stopped
    volumes:
      - /dev/urandom:/dev/random
    environment:
      - IRODS_ICAT_DBSERVER=icat-db
      - IRODS_ZONE_PORT=1247
      - IRODS_ZONE_NAME=tempZone
    ports:
      - 1247:1247
      - 20000-20199:20000-20199
    depends_on:
      - icat-db

volumes:
  pg_data:
    driver: local